version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    command: 
      - start-dev
    container_name: keycloak
    networks:
      - keycloak_net
        # ipv4_address: 192.168.208.10

  nginx:
    image: nginx
    volumes:
      - ../nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    container_name: nginx
    networks:
      - keycloak_net
        # ipv4_address: 192.168.208.20
networks:
  keycloak_net:
    name: keycloak_net
    external: true
  energy:
    name: energy
    external: true
